label_template option
kristijanhusak/laravel-form-builder pull request #700
Opened 2022-11-30 11:35 UTC by Eloar

new option for label template and moved rendering label to `label.php` template file for all templates with label. It simplifies extension of way label is rendered and allows to add custom html to labels. Works for every field (by extending `label.php` file) or for individual field (by providing `label_template` value pointing proper template file).

2022-11-30 16:16 UTC, rudiedirkx commented
I like it, BUT:

- You've committed some merge conflicts.
- And white-space is messy. Use indents like you do in `checkbox.php`.
- But more importantly, the fallback should be done like the help & error block:

```
<?php include helpBlockPath(); ?>
<?php include errorBlockPath(); ?>
```

instead of

```
<?php include 'label.php' ?>
```

so the dev can override the label in `views/vendor/laravel-form-builder/` for all labels always.

- And I feel like the 'if should show label' should be outside the label view:

```
<?php if ($showLabel && $options['label'] !== false && $options['label_show']): ?>
```

not inside it, but maybe I'm misunderstanding your goals. Can you give an example of a label override view? What's in there?

2022-12-01 22:41 UTC, rudiedirkx requested changes
That's getting good, buuutt now we're repeating this exact logic A LOT:

```php
<?php /** label rendering section */ ?>
<?php if ($showLabel && $options['label'] !== false && $options['label_show']): ?>
    <?php if(array_key_exists('label_template', $options) && $options['label_template']): ?>
        <?= view($options['label_template'], get_defined_vars())->render(); ?>
    <?php else: ?>
        <?php include labelBlockPath(); ?>
    <?php endif; ?>
<?php endif; ?>
```

Maybe we can create a form builder helper for that? Something that takes `get_defined_vars()` and does the same? A static function in `FormHelper`?, or is that evil?

2022-12-02 06:47 UTC, Eloar commented
Thought about some solution to reduce code repetition but there is plenty of it in form elements templates already. Like this exact code is repeated 12 times:

```php
<?php if ($options['wrapper'] !== false): ?>
<div <?= $options['wrapperAttrs'] ?> >
<?php endif; ?>
```

Not sure if new repetition becomes a problem as new helper methods or functions would be repeated just as much with this logic hidden inside. Although changing label visibility condition would need change in one file not 9. On the other hand changing that repeated code just for one form element type would be easier for package user as this logic would not be hidden in helper. I am bit conflicted regardless of that idea. 

Echo short tags (`<?= ?>`) are available even when `short_open_tag` setting is turned off on PHP interpreter. I believe it is so since PHP 5.4.  It is described on [echo page in docs](https://www.php.net/manual/en/function.echo.php).

2022-12-03 14:23 UTC, rudiedirkx commented
Well damn Github. I wrote a reply and Github threw it away.

----

short open tags: you're right, and we already use them, so ignore me.

repetition: I don't really mind either. Let's not add more helper functions.

2022-12-03 14:24 UTC, rudiedirkx requested changes
Aside from the `withoutDeprecationHandling()` I'm happy.

2022-12-03 14:24 UTC, rudiedirkx commented on tests/FormBuilderTestCase.php
> +        // $this->withoutDeprecationHandling();
Why? Deprecations are errors we should find, not silently ignore.

2022-12-09 16:22 UTC, rudiedirkx commented
You keep changing tests. Why? They work for me and for Github Actions. Is your test setup weird, or mine? Apparently they don't play nice together, because your exception change doesn't work.

2022-12-09 16:22 UTC, rudiedirkx commented
(You don't have to squash and rebase on your end. Github will do that when merging. That's easier to track PR progress.)

2022-12-10 06:20 UTC, Eloar commented
What makes my setup weird is I started from 1.22 version as it is last working with Laravel 5.5 (at least as I confirmed). I have legacy project in 5.5 that I want to use that feature in and it means I'm switching to my fork and using 1.23 tag. I started from 1.22 and fitted it to master which introduced trouble for pull request. Should have started other way around.

Fixed what I messed up in test so it should work now.

2022-12-16 19:46 UTC, rudiedirkx commented
You've committed a few cache files that should be in your `.gitignore`. We'll get there eventually =)

2022-12-16 21:07 UTC, Eloar commented
You are absolutely right, that should stay out of repo. Modified and pushed. Damn I'm clumsy with this one.

2022-12-17 19:37 UTC, rudiedirkx commented
I think we're done :+1: And if not, bring the reverts!

2022-12-17 19:37 UTC, merged